services:
  - type: web
    name: mindware-ai
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: Email_Password
        sync: false
      - key: SENDER_EMAIL
        sync: false
